### ISSUE TITLE
App fails when trying to open appearance settings

### ISSUE THREAD

**Issue by BANOnotIT** [breezy-weather/fdroid-repo#11]
I'm trying to change units from F to C but when I click on unit section app just fails.

**Comment by papjul** [comment]
Make sure you use v5.1.7 or later, and open an issue on the correct repo here: https://github.com/breezy-weather/breezy-weather/issues/new/choose

If it still reproduces, please extract a crash log from `Settings` > `Debug` and add it to your issue.
