### ISSUE TITLE
Empty space at the top

### ISSUE THREAD

**Issue by ezzra** [breezy-weather/fdroid-repo#8]
I had this problem also with the original app, the panels only start at the very bottom of the display and there is ahuge enpty space st the top when opening the app. Wirh breezy weather its just slightly better because there are more information above the panel but still there is a lot of annoying free space. Is this a bug or am Iam missing an option? Iam using a Pixel8

![Screenshot_20231017-112820](https://github.com/breezy-weather/fdroid-repo/assets/37742522/00376b96-2701-4880-ae7e-fa42693217b8)
![Screenshot_20231017-113331](https://github.com/breezy-weather/fdroid-repo/assets/37742522/5d1d7ee1-815b-49c5-bc41-a2625c16754e)

**Comment by papjul** [comment]
This is the GitHub repo for the F-Droid repo, please use Discussions tab from Breezy Weather app to ask questions ;)
